export interface IKullaniciDTO{
    id: number;
    kullaniciAdi: string;
    ad: string;
    soyad?: string;
    email?: string;
    kimlikNo: string;
    doktorMu: boolean
    yetkiGrupId: any;
    telefon?: string;
    resim?: any;
    resimContentType: any;
    resimYolu?: any;
    dogumTarihi: any;
    hbysKullanici: any;
    titresimAktif: boolean;
    sesAktif: boolean;
    bildirimAktif: boolean;
    tumHastalariGorebilir: boolean;
    yoneticiMi: boolean;
    musHizmetleriMi: boolean;
    pasifMi: boolean;
    pasifEdenPersonel: any;
    pasifEden: any;
    kullaniciId: number;
    tipi: any;
    sifreTarihi: any;
    sifreSuresi: number;
    sifreDegistirebilir: boolean;
    sonOturumTarihi: any;
    oturumSayisi: any;
    hataliSifreSayisi: any;
    bildirims: any;
    belges: any;
    cv?: any;
}